version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
      - ./artisan.db:/app/artisan.db
      - ./.env:/app/.env:ro
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
